# Generated by Django 5.1.1 on 2024-10-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asdf", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dealer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
