# Generated by Django 5.1.1 on 2024-10-19 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asdf", "0002_dealer"),
    ]

    operations = [
        migrations.AddField(
            model_name="drawn_card",
            name="dealer",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="asdf.dealer"
            ),
            preserve_default=False,
        ),
    ]
