# Generated by Django 5.1.1 on 2024-10-19 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asdf", "0003_drawn_card_dealer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dealer",
            old_name="user_id",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="drawn_card",
            name="dealer",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="asdf.dealer"
            ),
        ),
        migrations.AlterField(
            model_name="drawn_card",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
