# Generated by Django 5.1.1 on 2024-10-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asdf", "0004_rename_user_id_dealer_name_alter_drawn_card_dealer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealer",
            name="turns",
            field=models.IntegerField(default=0),
        ),
    ]
