# Generated by Django 5.1.1 on 2024-11-03 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asdf", "0005_dealer_turns"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventory_equipment",
            old_name="detected",
            new_name="protected",
        ),
    ]
